### ISSUE TITLE
Error getting authority

### ISSUE THREAD

**Issue by schnie** [mitel/dcos-rexray#2]
Thank you so much for this!  I'm a noobie to this stuff so forgive me if this is a dumb question.

I got all the way down to where we need to restart the mesos slave service.  I keep getting this error:

```
core@ip-10-0-0-30 ~ $ sudo systemctl stop dcos-mesos-slave.service
Error getting authority: Error initializing authority: Error calling StartServiceByName for org.freedesktop.PolicyKit1: Timeout was reached (g-io-error-quark, 24)
Failed to stop dcos-mesos-slave.service: Connection timed out
Failed to get load state of dcos-mesos-slave.service: Connection timed out
```

Any ideas?  Thanks!

**Comment by mitel** [comment]
Hello @schnie, have you tried to reinitialise systemd? Like rebooting the node. I think i got stuck one time on this and had to take it from scratch..
