### ISSUE TITLE
Package from installation link doesn't work with ec2 driver

### ISSUE THREAD

**Issue by alexandrst88** [mitel/dcos-rexray#4]
Hi! Big thanks for the documentaion, but I faced the issue with version of **rexray** when install it via link that you provided.
curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -s stable

When I was installed  via it, I got exeption
**invalid driver name**

Link that works with AWS(ec2 driver) is 
curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -s -- stable 0.3.3

**Comment by vitosans** [comment]
You need to use the new configuration format. I have forked this and am going to update it as I am learning this as well, then will submit a pull request.
